### ISSUE TITLE
Stocks Endpoint has no params

### ISSUE THREAD

**Issue by silentrob** [evzaboun/twelvedata#1]
For the /stocks endpoint, there is no params required. This may be the case for other endpoints as well.

`url = url.replace("{indicator}", params.indicator); // create indicator endpoint.`
 
 Needs to be tweaked in this case.

**Comment by fizampou** [comment]
Thanks for reporting this one.

https://github.com/evzaboun/twelvedata/pull/5

here is the fix. Will be release soon
